### ISSUE TITLE
Setting Fan Mode and Swing Mode does not work in FAN and DRY modes

### ISSUE THREAD

**Issue by felixmueller** [erwindouna/python-tado#57]
# Problem/Motivation

Starting with release 2024.7, Home Assistant supports setting the Fan Mode and Swing Mode for Tado AC Controls. But changing the Fan Mode and Swing Mode in HA does not work in FAN and DRY modes. As @EtienneSOU mentioned in https://github.com/home-assistant/core/issues/95389, the cause seems to be this library.

## Expected behavior

Setting Fan Mode and Swing Mode does also work in FAN and DRY modes

## Actual behavior

Setting Fan Mode and Swing Mode does not work in FAN and DRY modes

## Steps to reproduce

Try to set Fan Mode and Swing Mode while running in FAN or DRY mode

## Proposed changes

Add support for setting the Fan Mode and Swing Mode while running in FAN or DRY modes

Please consult issue https://github.com/home-assistant/core/issues/95389 for further details.

Thank you so much!

**Comment by erwindouna** [comment]
Thanks for reporting, this library is still in development and not yet actively used within Home Assistant. It will in time and this will be announced. 
Your described issue is thankfully already picked up by Etienne in: https://github.com/home-assistant/core/issues/121120#issuecomment-2216903797.

**Comment by 03397** [comment]
@erwindouna 
This will handle all the different fan modes?
I can test if you guide me through how to install the testing version.

**Comment by felixmueller** [comment]
Update: Bug still present in HA Core 2024.8.

**Comment by infestonn** [comment]
Sad
